### ISSUE TITLE
Doesn’t work on GNOME 41

### ISSUE THREAD

**Issue by ai** [alecdotninja/no-titlebar-when-maximized#1]
I have GNOME 41, Fedora 35 and VS Code. After extension was enabled (from [extensions.gnome.org](https://extensions.gnome.org/extension/4630/no-titlebar-when-maximized/)), I still have old behavior.

![Снимок экрана от 2021-11-29 01-13-26](https://user-images.githubusercontent.com/19343/143792114-4eb77919-f980-4915-959e-8df44723f253.png)

**Comment by alecdotninja** [comment]
Hmm, I am using GNOME 41 and VSCodium, and it works for me. Do you have `xprop` [installed](https://command-not-found.com/xprop) and in your path?

Also, do you see any errors in GNOME Shell's log (`journalctl --user -f /usr/bin/gnome-shell`) while maximizing/restoring the window?

**Comment by ai** [comment]
Got it. My mistake was in not installing `xprop`.

Can we add `xprop` note to extension description and to the top of GitHub docs to prevent others from the same mistake?

**Comment by alecdotninja** [comment]
That's a great idea. I've updated [the README](https://github.com/alecdotninja/no-titlebar-when-maximized/commit/2cb194c716926328f73b705f5b306c36a20c9b33) and [the description on the GNOME extentions website](https://extensions.gnome.org/extension/4630/no-titlebar-when-maximized/) to try to make the `xprop` requirement more clear. If you have any suggestions for additional changes, let me know :smile:

**Comment by ai** [comment]
Thanks for useful extension
