### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by MikeWent** [alecdotninja/no-titlebar-when-maximized#16]
Extension doesn't currently support GNOME 45 and is marked as Incompatible on [extensions.gnome.org](https://extensions.gnome.org/extension/4630/no-titlebar-when-maximized/).

GNOME 45 is in Arch Linux repos already :)

**Comment by peter-kehl** [comment]
Please upload to extensions.gnome.org. Currently it's only up to GNOME 44:
![image](https://github.com/alecdotninja/no-titlebar-when-maximized/assets/4270240/cbe7c129-73dc-4e21-94f6-24ee622a7e9f)

**Comment by kron4eg** [comment]
@peter-kehl the [review](https://extensions.gnome.org/review/47731) has been rejected. See more at https://github.com/alecdotninja/no-titlebar-when-maximized/pull/18#issuecomment-1805064481

**Comment by kron4eg** [comment]
BTW, @alecdotninja please reopen this issue.

**Comment by Tommimon** [comment]
Even if review has been rejected, a release compatible with GNOME 45 here on GitHub would be appreciated

**Comment by alecdotninja** [comment]
This is now available on the GNOME store.  😄
