### ISSUE TITLE
Add support for non-gtk applications

### ISSUE THREAD

**Issue by fikovnik** [alecdotninja/no-titlebar-when-maximized#2]
Would it be possible to add support for non-gtk applications? For example st terminal does not work nor does any of the qt apps I have installed.

**Comment by alecdotninja** [comment]
@fikovnik Do they work if you force them to connect via X.Org instead of Wayland (i.e. run with `GDK_BACKEND` and `QT_QPA_PLATFORM` environment variables set to `x11`)?

**Comment by fikovnik** [comment]
I only use X11, no wayland. Eventually, I found that the https://github.com/velitasali/gtktitlebar extensions works for all apps.

**Comment by alecdotninja** [comment]
I was able to reproduce this issue with Spotify, and I think I have fixed it.

Please feel free to reopen this issue if you are still seeing this behavior with the latest version of the extension. :slightly_smiling_face:
