### ISSUE TITLE
GNOME 42 version bump

### ISSUE THREAD

**Issue by jacknicklenson** [alecdotninja/no-titlebar-when-maximized#3]
Hi

In gnome 42 it is not work, probably metadata version bump needed.

Thx for extension btw :)

![image](https://user-images.githubusercontent.com/90291236/163280938-40e64343-ee9a-4998-9f77-387871829fb7.png)

**Comment by alecdotninja** [comment]
Thank you for letting me know!

A version with the updated metadata is now submitted to Gnome. :)
